-- MySQL Script generated by MySQL Workbench
-- Sat Aug 19 09:12:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seniorLearning
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seniorLearning` ;

-- -----------------------------------------------------
-- Schema seniorLearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seniorLearning` DEFAULT CHARACTER SET utf8 ;
USE `seniorLearning` ;

-- -----------------------------------------------------
-- Table `seniorLearning`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seniorLearning`.`user` ;

CREATE TABLE IF NOT EXISTS `seniorLearning`.`user` (
  `user_id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `tel` VARCHAR(11) NULL,
  `usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seniorLearning`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seniorLearning`.`product_type` ;

CREATE TABLE IF NOT EXISTS `seniorLearning`.`product_type` (
  `pt_id` INT NOT NULL,
  `pt_name` VARCHAR(45) NULL,
  `pt_parent` INT NULL,
  PRIMARY KEY (`pt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seniorLearning`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seniorLearning`.`provider` ;

CREATE TABLE IF NOT EXISTS `seniorLearning`.`provider` (
  `provider_id` INT NOT NULL,
  `provider_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `providercol` VARCHAR(45) NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seniorLearning`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seniorLearning`.`product` ;

CREATE TABLE IF NOT EXISTS `seniorLearning`.`product` (
  `product_id` BIGINT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_type_id` INT NULL,
  `image` VARCHAR(45) NULL,
  `tips` VARCHAR(450) NULL,
  `standard_price` DECIMAL NULL,
  `youhui` VARCHAR(45) NULL,
  `provider_type_id` INT NULL,
  `productcol` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
