-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 11:00:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seniorLearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seniorLearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seniorLearning` DEFAULT CHARACTER SET utf8 ;
USE `seniorLearning` ;

-- -----------------------------------------------------
-- Table `seniorLearning`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seniorLearning`.`user` (
  `user_id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
